#!/bin/bash
export WINEPREFIX=$(pwd)/wine
export WINEARCH=win64
case "$1" in
	init)
		winecfg
		wget -P ./wine https://www.python.org/ftp/python/3.6.4/python-3.6.4-amd64.exe
		wine wine/python-3.6.4-amd64.exe /quiet InstallAllUsers=1 PrependPath=1
		wine pip install gevent flask pywin32 flask-cors
		wine pip install pyinstaller
		;;
	build)
		wine pyinstaller namsd.spec
		;;
	clean)
		rm -rf *.pyc build/ dist/
		;;
	deepclean)
		rm -rf *.pyc build/ dist/ wine/
		;;
	*)
		echo $"Usage: $0 {init|build|clean|deepclean}"
		exit 1
esac
